# Copyright (C) 2026 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
#
name: video-accuracy-evaluation
services:
  nginx:
    image: nginxinc/nginx-unprivileged:1.29.1
    ports:
      - "8101:8080"
    volumes:
      - ../nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - video-accuracy-eval
      - video-accuracy-eval-ui

  video-accuracy-eval:
    image: video-accuracy-eval:latest
    container_name: video-accuracy-eval
    build:
      context: ../
      dockerfile: docker/Dockerfile
    environment:
      http_proxy: ${http_proxy}
      https_proxy: ${https_proxy}
      no_proxy: ${no_proxy}
      HF_TOKEN: ${HUGGINGFACEHUB_API_TOKEN}
      SBERT_MODEL_ID: ${SBERT_MODEL_ID}
      NLTK_ALLOW_PROXIED_URLOPEN: 1
    group_add:
      - ${USER_GROUP_ID-1000}
    ports:
      - "127.0.0.1:9000:9000"
    volumes:
      - "${MODEL_CACHE_PATH}:/tmp/model_cache"

  video-accuracy-eval-ui:
    image: video-accuracy-eval-ui:latest
    container_name: video-accuracy-eval-ui
    build:
      context: ../ui/
      dockerfile: docker/Dockerfile
    environment:
      http_proxy: ${http_proxy}
      https_proxy: ${https_proxy}
      no_proxy: ${no_proxy}, video-accuracy-eval, video-accuracy-eval-ui
      APP_BACKEND_URL: ${APP_BACKEND_URL}
    ports:
      - "127.0.0.1:5174:7860"
    depends_on:
      - video-accuracy-eval

networks:
  default:
    driver: bridge
